apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    version: 1
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    jsonData:
      host: clickhouse
      port: 8123
      username: default
      database: snt_ai
      tls: false
    access: proxy
    isDefault: false
    editable: true
    version: 1
