"""Initial migration

Revision ID: 1362ec1a5eda
Revises: 
Create Date: 2026-07-13 05:14:48.398332
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1362ec1a5eda'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
