"""Add stripe_customer_id

Revision ID: fda1b6fd524d
Revises: 1362ec1a5eda
Create Date: 2026-07-13 05:16:27.301892
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fda1b6fd524d'
down_revision: Union[str, None] = '1362ec1a5eda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('organizations_stripe_customer_id_idx'), 'organizations', ['stripe_customer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('organizations_stripe_customer_id_idx'), table_name='organizations')
    op.drop_column('organizations', 'stripe_customer_id')
    # ### end Alembic commands ###
